// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjson4e1b3cc1DecodeGithubComJackalLabsBurrowContractsCw1WhitelistSrcTypes(in *jlexer.Lexer, out *State) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "example_field":
			out.ExampleStateField = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson4e1b3cc1EncodeGithubComJackalLabsBurrowContractsCw1WhitelistSrcTypes(out *jwriter.Writer, in State) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"example_field\":"
		out.RawString(prefix[1:])
		out.String(string(in.ExampleStateField))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v State) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson4e1b3cc1EncodeGithubComJackalLabsBurrowContractsCw1WhitelistSrcTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v State) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson4e1b3cc1EncodeGithubComJackalLabsBurrowContractsCw1WhitelistSrcTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *State) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson4e1b3cc1DecodeGithubComJackalLabsBurrowContractsCw1WhitelistSrcTypes(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *State) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson4e1b3cc1DecodeGithubComJackalLabsBurrowContractsCw1WhitelistSrcTypes(l, v)
}
func tinyjson4e1b3cc1DecodeGithubComJackalLabsBurrowContractsCw1WhitelistSrcTypes1(in *jlexer.Lexer, out *AdminList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "admins":
			if in.IsNull() {
				in.Skip()
				out.Admins = nil
			} else {
				in.Delim('[')
				if out.Admins == nil {
					if !in.IsDelim(']') {
						out.Admins = make([]string, 0, 4)
					} else {
						out.Admins = []string{}
					}
				} else {
					out.Admins = (out.Admins)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.Admins = append(out.Admins, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "mutable":
			out.Mutable = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson4e1b3cc1EncodeGithubComJackalLabsBurrowContractsCw1WhitelistSrcTypes1(out *jwriter.Writer, in AdminList) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"admins\":"
		out.RawString(prefix[1:])
		if in.Admins == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Admins {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"mutable\":"
		out.RawString(prefix)
		out.Bool(bool(in.Mutable))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdminList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson4e1b3cc1EncodeGithubComJackalLabsBurrowContractsCw1WhitelistSrcTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v AdminList) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson4e1b3cc1EncodeGithubComJackalLabsBurrowContractsCw1WhitelistSrcTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdminList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson4e1b3cc1DecodeGithubComJackalLabsBurrowContractsCw1WhitelistSrcTypes1(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *AdminList) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson4e1b3cc1DecodeGithubComJackalLabsBurrowContractsCw1WhitelistSrcTypes1(l, v)
}
