// Code generated by tinyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	types "github.com/CosmWasm/cosmwasm-go/std/types"
	tinyjson "github.com/CosmWasm/tinyjson"
	jlexer "github.com/CosmWasm/tinyjson/jlexer"
	jwriter "github.com/CosmWasm/tinyjson/jwriter"
)

// suppress unused package warning
var (
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ tinyjson.Marshaler
)

func tinyjson68aa2349DecodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes(in *jlexer.Lexer, out *NativeBalance) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "coins":
			if in.IsNull() {
				in.Skip()
				out.Coins = nil
			} else {
				in.Delim('[')
				if out.Coins == nil {
					if !in.IsDelim(']') {
						out.Coins = make([]types.Coin, 0, 2)
					} else {
						out.Coins = []types.Coin{}
					}
				} else {
					out.Coins = (out.Coins)[:0]
				}
				for !in.IsDelim(']') {
					var v1 types.Coin
					(v1).UnmarshalTinyJSON(in)
					out.Coins = append(out.Coins, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson68aa2349EncodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes(out *jwriter.Writer, in NativeBalance) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"coins\":"
		out.RawString(prefix[1:])
		if in.Coins == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Coins {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalTinyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NativeBalance) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson68aa2349EncodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v NativeBalance) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson68aa2349EncodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NativeBalance) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson68aa2349DecodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *NativeBalance) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson68aa2349DecodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes(l, v)
}
func tinyjson68aa2349DecodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes1(in *jlexer.Lexer, out *Expiration) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "at_height":
			out.AtHeight = uint64(in.Uint64())
		case "at_time":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.AtTime).UnmarshalJSON(data))
			}
		case "never":
			out.Never = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson68aa2349EncodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes1(out *jwriter.Writer, in Expiration) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"at_height\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.AtHeight))
	}
	{
		const prefix string = ",\"at_time\":"
		out.RawString(prefix)
		out.Raw((in.AtTime).MarshalJSON())
	}
	{
		const prefix string = ",\"never\":"
		out.RawString(prefix)
		out.Bool(bool(in.Never))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Expiration) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson68aa2349EncodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v Expiration) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson68aa2349EncodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Expiration) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson68aa2349DecodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes1(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *Expiration) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson68aa2349DecodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes1(l, v)
}
func tinyjson68aa2349DecodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes2(in *jlexer.Lexer, out *Duration) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "height":
			out.Height = uint64(in.Uint64())
		case "time":
			out.Time = uint64(in.Uint64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func tinyjson68aa2349EncodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes2(out *jwriter.Writer, in Duration) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"height\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.Height))
	}
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Time))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Duration) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	tinyjson68aa2349EncodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalTinyJSON supports tinyjson.Marshaler interface
func (v Duration) MarshalTinyJSON(w *jwriter.Writer) {
	tinyjson68aa2349EncodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Duration) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	tinyjson68aa2349DecodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes2(&r, v)
	return r.Error()
}

// UnmarshalTinyJSON supports tinyjson.Unmarshaler interface
func (v *Duration) UnmarshalTinyJSON(l *jlexer.Lexer) {
	tinyjson68aa2349DecodeGithubComJackalLabsBurrowContractsCw1SubkeysSrcTypes2(l, v)
}
